### ISSUE TITLE
Make TAD multi language / translatable

### ISSUE THREAD

**Issue by ChristopherSpelt** [MinBZK/tad#49]
At the moment, we don't have much text. Still, I think it's a good idea to start making the Web UI translatable. For example, Algoritmeregister support Dutch, English, and Frysk.

## Deliverable
- Support for selecting a language
- Available languages: Dutch and English
- Nice to have: Frysk

**Comment by uittenbroekrobbert** [comment]
When we use cookies for language, do we need to ask for 'cookie permissions'. If so, we may want to use another solution.
